package com.zhiyi.mjxgz.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BusinessCoupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.business_id
     *
     * @mbggenerated
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.coupon_img
     *
     * @mbggenerated
     */
    private String couponImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.coupon_name
     *
     * @mbggenerated
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.coupon_title
     *
     * @mbggenerated
     */
    private String couponTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.active_type
     *
     * @mbggenerated
     */
    private Integer activeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.active_day
     *
     * @mbggenerated
     */
    private BigDecimal activeDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.goods_id
     *
     * @mbggenerated
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_coupon.coupon_type
     *
     * @mbggenerated
     */
    private Integer couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_coupon
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.id
     *
     * @return the value of business_coupon.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.id
     *
     * @param id the value for business_coupon.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.code
     *
     * @return the value of business_coupon.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.code
     *
     * @param code the value for business_coupon.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.describe
     *
     * @return the value of business_coupon.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.describe
     *
     * @param describe the value for business_coupon.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.start_time
     *
     * @return the value of business_coupon.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.start_time
     *
     * @param startTime the value for business_coupon.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.end_time
     *
     * @return the value of business_coupon.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.end_time
     *
     * @param endTime the value for business_coupon.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.business_id
     *
     * @return the value of business_coupon.business_id
     *
     * @mbggenerated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.business_id
     *
     * @param businessId the value for business_coupon.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.sort
     *
     * @return the value of business_coupon.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.sort
     *
     * @param sort the value for business_coupon.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.status
     *
     * @return the value of business_coupon.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.status
     *
     * @param status the value for business_coupon.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.coupon_img
     *
     * @return the value of business_coupon.coupon_img
     *
     * @mbggenerated
     */
    public String getCouponImg() {
        return couponImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.coupon_img
     *
     * @param couponImg the value for business_coupon.coupon_img
     *
     * @mbggenerated
     */
    public void setCouponImg(String couponImg) {
        this.couponImg = couponImg == null ? null : couponImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.coupon_name
     *
     * @return the value of business_coupon.coupon_name
     *
     * @mbggenerated
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.coupon_name
     *
     * @param couponName the value for business_coupon.coupon_name
     *
     * @mbggenerated
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.coupon_title
     *
     * @return the value of business_coupon.coupon_title
     *
     * @mbggenerated
     */
    public String getCouponTitle() {
        return couponTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.coupon_title
     *
     * @param couponTitle the value for business_coupon.coupon_title
     *
     * @mbggenerated
     */
    public void setCouponTitle(String couponTitle) {
        this.couponTitle = couponTitle == null ? null : couponTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.active_type
     *
     * @return the value of business_coupon.active_type
     *
     * @mbggenerated
     */
    public Integer getActiveType() {
        return activeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.active_type
     *
     * @param activeType the value for business_coupon.active_type
     *
     * @mbggenerated
     */
    public void setActiveType(Integer activeType) {
        this.activeType = activeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.active_day
     *
     * @return the value of business_coupon.active_day
     *
     * @mbggenerated
     */
    public BigDecimal getActiveDay() {
        return activeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.active_day
     *
     * @param activeDay the value for business_coupon.active_day
     *
     * @mbggenerated
     */
    public void setActiveDay(BigDecimal activeDay) {
        this.activeDay = activeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.create_time
     *
     * @return the value of business_coupon.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.create_time
     *
     * @param createTime the value for business_coupon.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.modify_time
     *
     * @return the value of business_coupon.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.modify_time
     *
     * @param modifyTime the value for business_coupon.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.goods_id
     *
     * @return the value of business_coupon.goods_id
     *
     * @mbggenerated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.goods_id
     *
     * @param goodsId the value for business_coupon.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_coupon.coupon_type
     *
     * @return the value of business_coupon.coupon_type
     *
     * @mbggenerated
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_coupon.coupon_type
     *
     * @param couponType the value for business_coupon.coupon_type
     *
     * @mbggenerated
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_coupon
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", describe=").append(describe);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", businessId=").append(businessId);
        sb.append(", sort=").append(sort);
        sb.append(", status=").append(status);
        sb.append(", couponImg=").append(couponImg);
        sb.append(", couponName=").append(couponName);
        sb.append(", couponTitle=").append(couponTitle);
        sb.append(", activeType=").append(activeType);
        sb.append(", activeDay=").append(activeDay);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", couponType=").append(couponType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}