package com.zhiyi.mjxgz.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Business implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.telphone
     *
     * @mbggenerated
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.linkman
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.certificate
     *
     * @mbggenerated
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.main_business
     *
     * @mbggenerated
     */
    private String mainBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_start
     *
     * @mbggenerated
     */
    private String businessStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_end
     *
     * @mbggenerated
     */
    private String businessEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.active_time
     *
     * @mbggenerated
     */
    private Date activeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.region_name
     *
     * @mbggenerated
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.grade
     *
     * @mbggenerated
     */
    private BigDecimal grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.welfare_content
     *
     * @mbggenerated
     */
    private String welfareContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.special_remind
     *
     * @mbggenerated
     */
    private String specialRemind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.modify_user_id
     *
     * @mbggenerated
     */
    private Long modifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_introduction
     *
     * @mbggenerated
     */
    private String businessIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.name
     *
     * @return the value of business.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.name
     *
     * @param name the value for business.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.telphone
     *
     * @return the value of business.telphone
     *
     * @mbggenerated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.telphone
     *
     * @param telphone the value for business.telphone
     *
     * @mbggenerated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.logo
     *
     * @return the value of business.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.logo
     *
     * @param logo the value for business.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.linkman
     *
     * @return the value of business.linkman
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.linkman
     *
     * @param linkman the value for business.linkman
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.status
     *
     * @return the value of business.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.status
     *
     * @param status the value for business.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.account_id
     *
     * @return the value of business.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.account_id
     *
     * @param accountId the value for business.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.certificate
     *
     * @return the value of business.certificate
     *
     * @mbggenerated
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.certificate
     *
     * @param certificate the value for business.certificate
     *
     * @mbggenerated
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate == null ? null : certificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.main_business
     *
     * @return the value of business.main_business
     *
     * @mbggenerated
     */
    public String getMainBusiness() {
        return mainBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.main_business
     *
     * @param mainBusiness the value for business.main_business
     *
     * @mbggenerated
     */
    public void setMainBusiness(String mainBusiness) {
        this.mainBusiness = mainBusiness == null ? null : mainBusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_start
     *
     * @return the value of business.business_start
     *
     * @mbggenerated
     */
    public String getBusinessStart() {
        return businessStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_start
     *
     * @param businessStart the value for business.business_start
     *
     * @mbggenerated
     */
    public void setBusinessStart(String businessStart) {
        this.businessStart = businessStart == null ? null : businessStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_end
     *
     * @return the value of business.business_end
     *
     * @mbggenerated
     */
    public String getBusinessEnd() {
        return businessEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_end
     *
     * @param businessEnd the value for business.business_end
     *
     * @mbggenerated
     */
    public void setBusinessEnd(String businessEnd) {
        this.businessEnd = businessEnd == null ? null : businessEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.active_time
     *
     * @return the value of business.active_time
     *
     * @mbggenerated
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.active_time
     *
     * @param activeTime the value for business.active_time
     *
     * @mbggenerated
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.province_name
     *
     * @return the value of business.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.province_name
     *
     * @param provinceName the value for business.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.city_name
     *
     * @return the value of business.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.city_name
     *
     * @param cityName the value for business.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.region_name
     *
     * @return the value of business.region_name
     *
     * @mbggenerated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.region_name
     *
     * @param regionName the value for business.region_name
     *
     * @mbggenerated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.grade
     *
     * @return the value of business.grade
     *
     * @mbggenerated
     */
    public BigDecimal getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.grade
     *
     * @param grade the value for business.grade
     *
     * @mbggenerated
     */
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.welfare_content
     *
     * @return the value of business.welfare_content
     *
     * @mbggenerated
     */
    public String getWelfareContent() {
        return welfareContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.welfare_content
     *
     * @param welfareContent the value for business.welfare_content
     *
     * @mbggenerated
     */
    public void setWelfareContent(String welfareContent) {
        this.welfareContent = welfareContent == null ? null : welfareContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.special_remind
     *
     * @return the value of business.special_remind
     *
     * @mbggenerated
     */
    public String getSpecialRemind() {
        return specialRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.special_remind
     *
     * @param specialRemind the value for business.special_remind
     *
     * @mbggenerated
     */
    public void setSpecialRemind(String specialRemind) {
        this.specialRemind = specialRemind == null ? null : specialRemind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.remark
     *
     * @return the value of business.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.remark
     *
     * @param remark the value for business.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.create_user_id
     *
     * @return the value of business.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.create_user_id
     *
     * @param createUserId the value for business.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.create_time
     *
     * @return the value of business.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.create_time
     *
     * @param createTime the value for business.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.modify_user_id
     *
     * @return the value of business.modify_user_id
     *
     * @mbggenerated
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.modify_user_id
     *
     * @param modifyUserId the value for business.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.modify_time
     *
     * @return the value of business.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.modify_time
     *
     * @param modifyTime the value for business.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_introduction
     *
     * @return the value of business.business_introduction
     *
     * @mbggenerated
     */
    public String getBusinessIntroduction() {
        return businessIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_introduction
     *
     * @param businessIntroduction the value for business.business_introduction
     *
     * @mbggenerated
     */
    public void setBusinessIntroduction(String businessIntroduction) {
        this.businessIntroduction = businessIntroduction == null ? null : businessIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", telphone=").append(telphone);
        sb.append(", logo=").append(logo);
        sb.append(", linkman=").append(linkman);
        sb.append(", status=").append(status);
        sb.append(", accountId=").append(accountId);
        sb.append(", certificate=").append(certificate);
        sb.append(", mainBusiness=").append(mainBusiness);
        sb.append(", businessStart=").append(businessStart);
        sb.append(", businessEnd=").append(businessEnd);
        sb.append(", activeTime=").append(activeTime);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", cityName=").append(cityName);
        sb.append(", regionName=").append(regionName);
        sb.append(", grade=").append(grade);
        sb.append(", welfareContent=").append(welfareContent);
        sb.append(", specialRemind=").append(specialRemind);
        sb.append(", remark=").append(remark);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUserId=").append(modifyUserId);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", businessIntroduction=").append(businessIntroduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}