package com.zhiyi.mjxgz.model;

import java.io.Serializable;
import java.util.Date;

public class OperationLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_user
     *
     * @mbggenerated
     */
    private String operationUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.terminal_type
     *
     * @mbggenerated
     */
    private String terminalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.module_name
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_type
     *
     * @mbggenerated
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_desc
     *
     * @mbggenerated
     */
    private String operationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_ip
     *
     * @mbggenerated
     */
    private String operationIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_time
     *
     * @mbggenerated
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_operation_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.id
     *
     * @return the value of sys_operation_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.id
     *
     * @param id the value for sys_operation_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_user
     *
     * @return the value of sys_operation_log.operation_user
     *
     * @mbggenerated
     */
    public String getOperationUser() {
        return operationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_user
     *
     * @param operationUser the value for sys_operation_log.operation_user
     *
     * @mbggenerated
     */
    public void setOperationUser(String operationUser) {
        this.operationUser = operationUser == null ? null : operationUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.terminal_type
     *
     * @return the value of sys_operation_log.terminal_type
     *
     * @mbggenerated
     */
    public String getTerminalType() {
        return terminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.terminal_type
     *
     * @param terminalType the value for sys_operation_log.terminal_type
     *
     * @mbggenerated
     */
    public void setTerminalType(String terminalType) {
        this.terminalType = terminalType == null ? null : terminalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.module_name
     *
     * @return the value of sys_operation_log.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.module_name
     *
     * @param moduleName the value for sys_operation_log.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_type
     *
     * @return the value of sys_operation_log.operation_type
     *
     * @mbggenerated
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_type
     *
     * @param operationType the value for sys_operation_log.operation_type
     *
     * @mbggenerated
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_desc
     *
     * @return the value of sys_operation_log.operation_desc
     *
     * @mbggenerated
     */
    public String getOperationDesc() {
        return operationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_desc
     *
     * @param operationDesc the value for sys_operation_log.operation_desc
     *
     * @mbggenerated
     */
    public void setOperationDesc(String operationDesc) {
        this.operationDesc = operationDesc == null ? null : operationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_ip
     *
     * @return the value of sys_operation_log.operation_ip
     *
     * @mbggenerated
     */
    public String getOperationIp() {
        return operationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_ip
     *
     * @param operationIp the value for sys_operation_log.operation_ip
     *
     * @mbggenerated
     */
    public void setOperationIp(String operationIp) {
        this.operationIp = operationIp == null ? null : operationIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_time
     *
     * @return the value of sys_operation_log.operation_time
     *
     * @mbggenerated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_time
     *
     * @param operationTime the value for sys_operation_log.operation_time
     *
     * @mbggenerated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", operationUser=").append(operationUser);
        sb.append(", terminalType=").append(terminalType);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", operationType=").append(operationType);
        sb.append(", operationDesc=").append(operationDesc);
        sb.append(", operationIp=").append(operationIp);
        sb.append(", operationTime=").append(operationTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}