package com.zhiyi.mjxgz.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class VipOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.order_number
     *
     * @mbggenerated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.pay_status
     *
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.vip_meal_id
     *
     * @mbggenerated
     */
    private Integer vipMealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.order_amount
     *
     * @mbggenerated
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.pay_amount
     *
     * @mbggenerated
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_order.pay_error
     *
     * @mbggenerated
     */
    private String payError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.order_number
     *
     * @return the value of vip_order.order_number
     *
     * @mbggenerated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.order_number
     *
     * @param orderNumber the value for vip_order.order_number
     *
     * @mbggenerated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.pay_status
     *
     * @return the value of vip_order.pay_status
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.pay_status
     *
     * @param payStatus the value for vip_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.vip_meal_id
     *
     * @return the value of vip_order.vip_meal_id
     *
     * @mbggenerated
     */
    public Integer getVipMealId() {
        return vipMealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.vip_meal_id
     *
     * @param vipMealId the value for vip_order.vip_meal_id
     *
     * @mbggenerated
     */
    public void setVipMealId(Integer vipMealId) {
        this.vipMealId = vipMealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.order_amount
     *
     * @return the value of vip_order.order_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.order_amount
     *
     * @param orderAmount the value for vip_order.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.pay_amount
     *
     * @return the value of vip_order.pay_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.pay_amount
     *
     * @param payAmount the value for vip_order.pay_amount
     *
     * @mbggenerated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.remark
     *
     * @return the value of vip_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.remark
     *
     * @param remark the value for vip_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.account_id
     *
     * @return the value of vip_order.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.account_id
     *
     * @param accountId the value for vip_order.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.create_time
     *
     * @return the value of vip_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.create_time
     *
     * @param createTime the value for vip_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_order.pay_error
     *
     * @return the value of vip_order.pay_error
     *
     * @mbggenerated
     */
    public String getPayError() {
        return payError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_order.pay_error
     *
     * @param payError the value for vip_order.pay_error
     *
     * @mbggenerated
     */
    public void setPayError(String payError) {
        this.payError = payError == null ? null : payError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderNumber=").append(orderNumber);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", vipMealId=").append(vipMealId);
        sb.append(", orderAmount=").append(orderAmount);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", remark=").append(remark);
        sb.append(", accountId=").append(accountId);
        sb.append(", createTime=").append(createTime);
        sb.append(", payError=").append(payError);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}