package com.zhiyi.mjxgz.dao;

import com.zhiyi.mjxgz.model.AccountCoupon;
import com.zhiyi.mjxgz.model.AccountCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int countByExample(AccountCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int deleteByExample(AccountCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int insert(AccountCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int insertSelective(AccountCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    List<AccountCoupon> selectByExample(AccountCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    AccountCoupon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccountCoupon record, @Param("example") AccountCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccountCoupon record, @Param("example") AccountCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountCoupon record);
}