package com.zhiyi.mjxgz.dao;

import com.zhiyi.mjxgz.model.AccountJpush;
import com.zhiyi.mjxgz.model.AccountJpushExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountJpushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int countByExample(AccountJpushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int deleteByExample(AccountJpushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int insert(AccountJpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int insertSelective(AccountJpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    List<AccountJpush> selectByExample(AccountJpushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    AccountJpush selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccountJpush record, @Param("example") AccountJpushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccountJpush record, @Param("example") AccountJpushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountJpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_jpush
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountJpush record);
}