package com.zhiyi.mjxgz.dao;

import com.zhiyi.mjxgz.model.BusinessShop;
import com.zhiyi.mjxgz.model.BusinessShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int countByExample(BusinessShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int deleteByExample(BusinessShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int insert(BusinessShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int insertSelective(BusinessShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    List<BusinessShop> selectByExample(BusinessShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    BusinessShop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BusinessShop record, @Param("example") BusinessShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BusinessShop record, @Param("example") BusinessShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusinessShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_shop
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BusinessShop record);
}