package com.zhiyi.mjxgz.dao;

import com.zhiyi.mjxgz.model.BusinessImg;
import com.zhiyi.mjxgz.model.BusinessImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int countByExample(BusinessImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int deleteByExample(BusinessImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int insert(BusinessImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int insertSelective(BusinessImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    List<BusinessImg> selectByExample(BusinessImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    BusinessImg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BusinessImg record, @Param("example") BusinessImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BusinessImg record, @Param("example") BusinessImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusinessImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BusinessImg record);
}