package com.zhiyi.mjxgz.dao;

import com.zhiyi.mjxgz.model.RegionBusiness;
import com.zhiyi.mjxgz.model.RegionBusinessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegionBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int countByExample(RegionBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int deleteByExample(RegionBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int insert(RegionBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int insertSelective(RegionBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    List<RegionBusiness> selectByExample(RegionBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    RegionBusiness selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RegionBusiness record, @Param("example") RegionBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RegionBusiness record, @Param("example") RegionBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RegionBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RegionBusiness record);
}