package com.zhiyi.mjxgz.dao;

import com.zhiyi.mjxgz.model.VipMeal;
import com.zhiyi.mjxgz.model.VipMealExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipMealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int countByExample(VipMealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int deleteByExample(VipMealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int insert(VipMeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int insertSelective(VipMeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    List<VipMeal> selectByExample(VipMealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    VipMeal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VipMeal record, @Param("example") VipMealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VipMeal record, @Param("example") VipMealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VipMeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_meal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VipMeal record);
}